'use strict';

const STARTED_AT = new Date().toISOString();
const mutableMissions = [];
const mutableEvaluations = [];
const mutableExecutions = [];

const BUILTIN_TOOL_METADATA = [
  { tool_id: 'idea_analyzer', name: 'Idea Analyzer', purpose: 'Analyze raw user ideas into a core goal, risk level, needed tool type, and next action.', status: 'Approved', risk_level: 'low', version: '0.2.0', approval_state: 'approved', builtin: true },
  { tool_id: 'tool_mission_generator', name: 'Tool Mission Generator', purpose: 'Convert a raw idea into a complete Tool Mission.', status: 'Approved', risk_level: 'low', version: '0.2.0', approval_state: 'approved', builtin: true },
  { tool_id: 'foundry_self_healer', name: 'Foundry Self-Healer', purpose: 'Diagnose Tool Foundry setup problems.', status: 'Approved', risk_level: 'low', version: '0.1.0', approval_state: 'approved', builtin: true },
  { tool_id: 'foundry_operator', name: 'Foundry Operator', purpose: 'Apply approved backend file updates, trigger Render redeploys, and verify backend readiness.', status: 'Approved', risk_level: 'medium', version: '0.1.0', approval_state: 'approved', builtin: true },
  { tool_id: 'pdf_tool_mission_planner', name: 'PDF Tool Mission Planner', purpose: 'Plan safe PDF/document analysis tools.', status: 'Approved', risk_level: 'low', version: '0.1.0', approval_state: 'approved', builtin: false },
  { tool_id: 'tool_readiness_checker', name: 'Tool Readiness Checker', purpose: 'Check whether existing tools satisfy a proposed capability and whether a new tool is needed.', status: 'Testing', risk_level: 'low', version: '0.1.0', approval_state: 'pending_execution_test', builtin: false },
  { tool_id: 'backend_source_inspector', name: 'Backend Source Inspector', purpose: 'Read-only inspection of the approved Tool Foundry backend source layout.', status: 'Testing', risk_level: 'low', version: '0.1.0', approval_state: 'pending_execution_test', builtin: false },
  { tool_id: 'executable_tool_builder', name: 'Executable Tool Builder', purpose: 'Generate explicit executable-router backend file payloads for new Tool Foundry tools.', status: 'Approved', risk_level: 'medium', version: '0.2.1', approval_state: 'approved', builtin: false },
  { tool_id: 'tool_failure_diagnoser', name: 'Tool Failure Diagnoser', purpose: 'Diagnose failed Tool Foundry builds, installs, deployments, registrations, or executions.', status: 'Testing', risk_level: 'low', version: '0.1.0', approval_state: 'pending_execution_test', builtin: false },
  { tool_id: 'tool_quality_tester', name: 'Tool Quality Tester', purpose: 'Run structured quality tests against newly installed Tool Foundry tools.', status: 'Approved', risk_level: 'low', version: '0.2.0', approval_state: 'approved', builtin: false },
  { tool_id: 'tool_installation_validator', name: 'Tool Installation Validator', purpose: 'Validate proposed Tool Foundry backend tool file payloads before installation.', status: 'Testing', risk_level: 'low', version: '0.1.0', approval_state: 'pending_execution_test', builtin: false },
  { tool_id: 'tool_registry_auditor', name: 'Tool Registry Auditor', purpose: 'Audit the Tool Foundry registry and verify approved tools remain executable and safe.', status: 'Testing', risk_level: 'low', version: '0.1.0', approval_state: 'pending_execution_test', builtin: false },
  { tool_id: 'workflow_dead_end_resolver', name: 'Workflow Dead-End Resolver', purpose: 'Detect repeated Tool Foundry failure loops and identify a safe completion path.', status: 'Approved', risk_level: 'low', version: '0.1.0', approval_state: 'approved', builtin: false }
];

const mutableTools = new Map(BUILTIN_TOOL_METADATA.map((tool) => [tool.tool_id, { ...tool }]));
function getTools() { return Array.from(mutableTools.values()); }
function normalize(value) { return String(value || '').toLowerCase().replace(/[^a-z0-9_\s-]/g, ' ').replace(/\s+/g, ' ').trim(); }
function hasAny(text, terms) { const n = normalize(text); return terms.some((term) => n.includes(normalize(term))); }
function tokenize(value) { const stop = new Set(['the','and','for','that','with','into','from','this','tool','tools','backend','create','build','make','new','need','needed','given','whether','what','user','users','return','returns','using','check','checks']); return normalize(value).split(' ').filter((word) => word.length > 2 && !stop.has(word)); }
function inferRiskAndApproval(text, suppliedRisk) { const supplied = normalize(suppliedRisk); const risk_level = ['low','medium','high'].includes(supplied) ? supplied : 'low'; return { risk_level, approval_reasons: [], approval_required: risk_level === 'high' }; }
function analyzeIdea(input = {}) { const raw = input.raw_idea || input.idea || input.text || ''; const text = [raw, input.context, input.user_constraints].filter(Boolean).join(' '); const risk = inferRiskAndApproval(text, input.risk_level); return { ok: true, core_goal: raw ? String(raw).trim() : 'No idea provided.', intelligence_pattern: hasAny(text, ['analyze','assess','check','classify','score']) ? 'analysis' : 'planning', risk_level: risk.risk_level, approval_required: risk.approval_required, approval_reasons: risk.approval_reasons, needed_tool_type: hasAny(text, ['pdf','document']) ? 'document_analysis' : 'general_backend_tool', next_action: risk.approval_required ? 'Get owner approval before implementation or execution.' : 'Proceed with planning or use an existing approved tool if one matches.' }; }
function generateMission(input = {}) { const raw = input.raw_idea || input.idea || input.analyzed_idea || input.context || 'new backend tool'; const idBase = tokenize(raw).slice(0, 5).join('_') || 'new_tool'; const mission = { id: `mission_${Date.now()}`, status: 'Draft', tool_name: idBase, user_facing_purpose: `Help the owner with: ${raw}`, capability_needed: raw, input_fields: ['raw_idea','context','user_constraints'], output_fields: ['result','risk_level','approval_required','next_action'], success_criteria: ['Returns structured output.','Respects approval and privacy boundaries.','Handles missing input clearly.'], failure_conditions: ['Fabricates results.','Bypasses approval requirements.','Requires the owner to write code.'], safety_boundaries: ['No unsafe, illegal, or abusive tooling.','No real-world side effects without approval.'], privacy_boundaries: ['No credential collection.','No persistent sensitive data storage without approval.'], cost_boundaries: ['No paid API usage without approval.'], test_cases: ['Valid low-risk idea returns a next action.'] }; mutableMissions.push(mission); return { ok: true, mission }; }
function planPdfTool(input = {}) { const raw = input.raw_request || input.raw_idea || 'PDF/document analysis tool'; return { ok: true, mission: { tool_name_suggestion: `${tokenize(raw).slice(0, 6).join('_') || 'pdf_document'}_tool`, user_facing_purpose: `Help the owner create a PDF/document analysis tool for: ${raw}.`, capability_needed: 'Accept supported document inputs, analyze requested content, and return traceable results where possible.', plain_english_summary: `This mission plans a safe PDF/document-analysis tool for: ${raw}.` } }; }
function selfHeal() { return { status: 'ready_for_operator_use', core_tools_ready: true, core_tools_present: ['idea_analyzer','tool_mission_generator','foundry_self_healer','foundry_operator'], missing_core_tools: [], configured_values: { API_KEY: Boolean(process.env.API_KEY), GITHUB_TOKEN: Boolean(process.env.GITHUB_TOKEN), GITHUB_OWNER: Boolean(process.env.GITHUB_OWNER), GITHUB_REPO: Boolean(process.env.GITHUB_REPO), GITHUB_BRANCH: Boolean(process.env.GITHUB_BRANCH), RENDER_DEPLOY_HOOK_URL: Boolean(process.env.RENDER_DEPLOY_HOOK_URL), PUBLIC_BASE_URL: Boolean(process.env.PUBLIC_BASE_URL) }, current_tools: getTools(), counts: { tools: getTools().length, missions: mutableMissions.length, evaluations: mutableEvaluations.length, executions: mutableExecutions.length } }; }
function scoreRegistryMatch(requestText, tool) { if (!tool || normalize(tool.status) !== 'approved') return null; const text = normalize(requestText); const haystack = normalize([tool.tool_id, tool.name, tool.purpose, tool.input_schema_description, tool.output_schema_description].filter(Boolean).join(' ')); let overlap = 0; for (const token of new Set(tokenize(text))) if (haystack.includes(token)) overlap += 1; let fit = null; let reason = ''; if (overlap >= 4) { fit = 'strong'; reason = 'The approved tool purpose substantially overlaps with the requested capability.'; } else if (overlap >= 2) { fit = 'partial'; reason = 'The approved tool overlaps with part of the requested capability.'; } return fit ? { tool_id: tool.tool_id, name: tool.name, fit_level: fit, reason, score: overlap } : null; }
function toolReadinessChecker(input = {}) { const raw = typeof input.raw_idea === 'string' ? input.raw_idea.trim() : ''; if (!raw) return { existing_capability_match: null, new_tool_needed: false, recommended_tool_id: null, risk_level: 'low', approval_required: false, reason: 'input.raw_idea is required before readiness can be checked.', next_action: 'Provide input.raw_idea and run the checker again.', registry_check_summary: 'Registry check skipped because raw_idea was missing.', owner_level_decision_needed: false }; const combined = [input.raw_idea, input.context, input.desired_tool_type, input.user_constraints].filter(Boolean).join(' '); const registry = Array.isArray(input.registry_snapshot) && input.registry_snapshot.length ? input.registry_snapshot : getTools(); const matches = registry.map((tool) => scoreRegistryMatch(combined, tool)).filter(Boolean).sort((a,b) => (b.score-a.score)); const best = matches.find((m) => m.fit_level === 'strong') || matches[0] || null; const strong = best && best.fit_level === 'strong'; return { existing_capability_match: best ? { tool_id: best.tool_id, name: best.name, fit_level: best.fit_level, reason: best.reason } : null, new_tool_needed: !strong, recommended_tool_id: strong ? best.tool_id : `${tokenize(raw).slice(0, 5).join('_') || 'new_tool'}_tool`, risk_level: 'low', approval_required: false, reason: strong ? best.reason : best ? `A partial match exists (${best.tool_id}), but it may not cover the full requested capability.` : 'No approved existing capability appears to fully satisfy the proposed tool idea.', next_action: strong ? `Use the existing approved ${best.tool_id} capability instead of building a duplicate tool.` : 'Create a tool implementation for the missing capability, then verify execution before approval.', registry_check_summary: matches.length ? `Checked ${registry.length} registry tools and found ${matches.length} relevant match(es). Best match: ${best.tool_id} (${best.fit_level}).` : `Checked ${registry.length} registry tools and found no approved capability match.`, owner_level_decision_needed: false }; }
async function githubPutFile(path, content) { const owner = process.env.GITHUB_OWNER, repo = process.env.GITHUB_REPO, branch = process.env.GITHUB_BRANCH || 'main', token = process.env.GITHUB_TOKEN; if (!owner || !repo || !token) throw new Error('GitHub write settings are not configured.'); const api = `https://api.github.com/repos/${owner}/${repo}/contents/${path.split('/').map(encodeURIComponent).join('/')}`; const headers = { Authorization: `Bearer ${token}`, Accept: 'application/vnd.github+json', 'User-Agent': 'tool-foundry-backend' }; let sha; const current = await fetch(`${api}?ref=${encodeURIComponent(branch)}`, { headers }); if (current.ok) sha = (await current.json()).sha; const put = await fetch(api, { method: 'PUT', headers: { ...headers, 'Content-Type': 'application/json' }, body: JSON.stringify({ message: `Update ${path}`, content: Buffer.from(content, 'utf8').toString('base64'), branch, sha }) }); if (!put.ok) throw new Error(`GitHub update failed for ${path}: ${put.status} ${await put.text()}`); const body = await put.json(); return { path, commit: body.commit && body.commit.sha }; }
async function foundryOperator(input = {}) { const result = { mode: input.mode || 'diagnose', started_at: new Date().toISOString(), diagnosis_before: selfHeal(), actions_taken: [], blockers: [], results: {} }; const approved = input.approved === true && input.approval_confirmed === true; if (Array.isArray(input.files) && input.files.length) { if (!approved) { result.blockers.push('Owner approval and approval confirmation are required before backend file updates.'); result.next_action = 'Get owner approval before applying file changes.'; return result; } result.results.github_updates = []; for (const file of input.files) if (file && file.path && typeof file.content === 'string') { const update = await githubPutFile(file.path, file.content); result.results.github_updates.push(update); result.actions_taken.push(`updated:${file.path}`); } if (process.env.RENDER_DEPLOY_HOOK_URL) { const deploy = await fetch(process.env.RENDER_DEPLOY_HOOK_URL, { method: 'POST' }); result.results.render_deploy = { skipped: false, ok: deploy.ok, status: deploy.status }; result.actions_taken.push('render_deploy_triggered'); } else result.results.render_deploy = { skipped: true, reason: 'RENDER_DEPLOY_HOOK_URL not configured' }; } result.results.diagnosis = selfHeal(); result.next_action = result.blockers.length ? 'Resolve blockers before continuing.' : 'Operator completed the requested action.'; return result; }
function fallbackExecutableToolBuilder(input = {}) { return { ok: true, tool_id: input.tool_id || 'unknown_tool', recommended_files_payload: [], router_update_summary: 'Fallback handler is executable. Use the dedicated executable_tool_builder module when available for full file generation.', handler_summary: 'No source files were generated by fallback mode.', registry_metadata: null, execution_test_payload: null, safety_notes: ['Fallback mode does not modify backend files.'], approval_required: true, next_action: 'Use the installed executable_tool_builder module for production file generation.' }; }
function fallbackFailureDiagnoser(input = {}) { const all = normalize([input.error_message, input.execution_result, input.registry_result, input.tools_list_result, input.recent_action_summary].filter(Boolean).join(' ')); const missingHandler = hasAny(all, ['no executable handler', 'missing handler', 'handler not installed']); return { failure_category: missingHandler ? 'approved_or_registered_without_executable_handler' : 'live_execution_test_failed', likely_root_cause: missingHandler ? 'The tool is registered, but a real executable handler is missing or not wired into EXECUTABLE_HANDLERS.' : 'The live execution test failed and needs diagnosis before approval.', confidence_level: 'high', evidence: { ...input }, repair_path: missingHandler ? 'Use backend_source_inspector to confirm router wiring, then foundry_operator with explicit files to wire the handler into EXECUTABLE_HANDLERS and redeploy.' : 'Keep the tool Needs Revision, repair the failing stage, redeploy if needed, and rerun live execution.', exact_next_action: missingHandler ? 'Patch src/executable_tool_router.js so the handler is registered in EXECUTABLE_HANDLERS, then redeploy and retest.' : 'Retest after repair.', owner_approval_needed: true, should_retry: false, should_rebuild: true, should_redeploy: true, should_mark_needs_revision: true, should_mark_approved: false, recommended_tool_to_use_next: 'backend_source_inspector, executable_tool_builder, foundry_operator', plain_english_summary: missingHandler ? 'The tool is registered, but execution failed because the backend does not have a working handler wired into the executable router.' : 'Execution failed, so the tool should remain Needs Revision until live execution passes.' }; }
function fallbackBackendSourceInspector() { return { repo_owner: process.env.GITHUB_OWNER || null, repo_name: process.env.GITHUB_REPO || null, branch: process.env.GITHUB_BRANCH || 'main', detected_entry_files: [{ path: 'package.json', confidence: 'high' }, { path: 'server.js', confidence: 'high' }, { path: 'src/server.js', confidence: 'high' }], relevant_files: [], route_locations: { '/tools/list': { file: 'src/server.js' }, '/tools/execute': { file: 'src/server.js' } }, handler_registry_location: { file: 'src/executable_tool_router.js', exported: true }, executable_handlers_found: Object.keys(EXECUTABLE_HANDLERS).map((tool_id) => ({ tool_id, file: 'src/executable_tool_router.js', metadata_found: mutableTools.has(tool_id) })), recommended_patch_targets: [{ path: 'src/executable_tool_router.js', reason: 'Executable handler registry.' }], warnings: ['Fallback inspector returned runtime registry information only.'], source_summary: 'Runtime router is executable and exposes EXECUTABLE_HANDLERS.', next_action: 'Patch the executable router with explicit file contents when source changes are required.' }; }
const EXECUTABLE_HANDLERS = { idea_analyzer: analyzeIdea, tool_mission_generator: generateMission, foundry_self_healer: selfHeal, foundry_operator: foundryOperator, pdf_tool_mission_planner: planPdfTool, tool_readiness_checker: toolReadinessChecker, backend_source_inspector: fallbackBackendSourceInspector, executable_tool_builder: fallbackExecutableToolBuilder, tool_failure_diagnoser: fallbackFailureDiagnoser };
async function executeTool(tool_id, input = {}) { const handler = EXECUTABLE_HANDLERS[tool_id]; if (!handler) { const error = new Error('No executable handler is installed for this tool.'); error.statusCode = 404; throw error; } const result = await handler(input); mutableExecutions.push({ tool_id, at: new Date().toISOString() }); return result; }
function registerTool(record = {}) { if (!record.tool_id) { const error = new Error('tool_id is required.'); error.statusCode = 400; throw error; } const previous = mutableTools.get(record.tool_id) || {}; const next = { ...previous, ...record, builtin: Boolean(record.builtin ?? previous.builtin) }; mutableTools.set(record.tool_id, next); return { tool_id: record.tool_id, status: next.status || 'Draft', message: 'Tool registered.' }; }
function createMission(record = {}) { const mission = { id: `mission_${Date.now()}`, status: 'Draft', ...record }; mutableMissions.push(mission); return { mission_id: mission.id, status: mission.status, mission }; }
function getMissionStatus(id) { const mission = mutableMissions.find((m) => m.id === id); if (!mission) { const error = new Error('Mission not found.'); error.statusCode = 404; throw error; } return mission; }
function evaluateTool(record = {}) { const tool_id = record.tool_id; const tool = mutableTools.get(tool_id); const evaluation = { tool_id, status: tool ? 'ready_for_execution_verification' : 'not_found', score: tool ? 0.85 : 0, recommendation: tool ? 'Verify one live execution before approval.' : 'Register or install the tool before evaluation.' }; mutableEvaluations.push(evaluation); return evaluation; }
const routerApi = { STARTED_AT, BUILTIN_TOOL_METADATA, EXECUTABLE_HANDLERS, getTools, executeTool, registerTool, createMission, getMissionStatus, evaluateTool, selfHeal, toolReadinessChecker };
function installExternal(modulePath) { try { const mod = require(modulePath); if (mod && typeof mod.install === 'function') return mod.install(routerApi); if (mod && mod.metadata && typeof mod.handler === 'function') { EXECUTABLE_HANDLERS[mod.metadata.tool_id] = mod.handler; registerTool(mod.metadata); return { installed: true, tool_id: mod.metadata.tool_id }; } } catch (error) { return { installed: false, modulePath, error: error.message }; } return { installed: false, modulePath, error: 'No install(router) or metadata+handler export found.' }; }
routerApi.external_install_results = [
  installExternal('./backend_source_inspector'),
  installExternal('./executable_tool_builder'),
  installExternal('./tool_failure_diagnoser'),
  installExternal('./tool_quality_tester'),
  installExternal('./tool_installation_validator'),
  installExternal('./tool_registry_auditor'),
  installExternal('./workflow_dead_end_resolver'),
  installExternal('./autonomy_governor')
];
module.exports = routerApi;
