'use strict';
const METADATA={tool_id:'script_first_engineering_operator',name:'Script-First Engineering Operator',purpose:'Proactively recommend safe helper scripts, validators, parsers, test harnesses, benchmarks, and adapters that make programming and Tool Foundry workflows more reliable.',status:'Testing',risk_level:'low',version:'0.1.0',approval_state:'pending_execution_test',builtin:false,input_schema_description:'raw_idea; workflow_context; available_tools; codebase_summary; risk_constraints; approval_status',output_schema_description:'recommended_scripts; script_purposes; script_templates; expected_inputs_outputs; safety_classification; ephemeral_or_committed; execution_test_commands; integration_notes; owner_approval_needed; plain_english_summary'};
function text(v){if(v===null||v===undefined)return'';if(typeof v==='string')return v;try{return JSON.stringify(v)}catch(e){return String(v)}}
function has(s,terms){const x=text(s).toLowerCase();return terms.some(t=>x.includes(String(t).toLowerCase()))}
function approvalNeeded(s,a){return has(s,['delete','rm -rf','drop table','deploy','external api','paid api','secret','token','credential','password','send email','send message','permission','scheduled','public publish','production write'])&&!has(a,['approved:true','approval_confirmed:true','explicitly approved'])}
function mk(kind,name,purpose,template,input,output,note){return{kind,name,purpose,language:'python',risk_level:'low',read_only:true,ephemeral_or_committed:'ephemeral by default; commit-worthy only after review',template,expected_input:input,expected_output:output,test_command:`python ${name} --help || true`,integration_note:note}}
const templates={log:`import re,sys,json\ntext=sys.stdin.read()\nitems=re.findall(r'(ERROR.*|Exception.*|Traceback[\\s\\S]*)',text,re.I)\nprint(json.dumps({'matches':items[:50],'count':len(items)},indent=2))`,schema:`import json,sys\np=json.load(sys.stdin)\nerrs=[]\nif 'tool_id' not in p: errs.append('missing tool_id')\nif 'input' not in p or not isinstance(p.get('input'),dict): errs.append('input must be object')\nprint(json.dumps({'ok':not errs,'errors':errs},indent=2))\nsys.exit(1 if errs else 0)`,fixture:`import json\nprint(json.dumps({'tool_id':'target_tool','input':{'raw_idea':'sample task'}},indent=2))`,repro:`def run_case():\n    sample={'input':'smallest failing case'}\n    assert sample['input']\n    return sample\nprint(run_case())`,test:`def test_shape(r):\n    assert isinstance(r,dict)\n    assert 'plain_english_summary' in r\ntest_shape({'plain_english_summary':'ok'})\nprint('tests passed')`,bench:`import time\nstart=time.perf_counter()\nfor _ in range(1000): sum(range(1000))\nprint({'seconds':round(time.perf_counter()-start,6),'iterations':1000})`,inspect:`import os,json\nfiles=[]\nfor root,dirs,names in os.walk('.'):\n    dirs[:]=[d for d in dirs if d not in {'.git','node_modules','venv','__pycache__'}]\n    for n in names: files.append(os.path.join(root,n))\nprint(json.dumps({'files':files[:300],'count':len(files)},indent=2))`,deps:`import pathlib\nfor n in ['package.json','requirements.txt','pyproject.toml']:\n    p=pathlib.Path(n)\n    if p.exists(): print('## '+n+'\\n'+p.read_text()[:4000])`,adapter:`import json,sys\nraw=json.load(sys.stdin)\nprint(json.dumps({'tool_id':raw.get('tool_id','target_tool'),'input':raw.get('input',raw)},indent=2))`};
function execute(input={}){const combined=[input.raw_idea,input.workflow_context,input.available_tools,input.codebase_summary,input.risk_constraints,input.approval_status].map(text).join('\n');const scripts=[];const add=s=>{if(!scripts.some(x=>x.kind===s.kind))scripts.push(s)};
if(has(combined,['log','traceback','exception','messy','error output']))add(mk('log_parser','log_parser_extract_errors.py','Extract errors, exceptions, and failure signatures from messy logs.',templates.log,'Raw logs on stdin.','JSON error matches and count.','Feed into tool_failure_diagnoser or repair prompts.'));
if(has(combined,['schema','payload','contract','validator','shape','tool call','json'])){add(mk('schema_validator','payload_schema_validator.py','Validate Tool Foundry payload shape before downstream tool calls.',templates.schema,'JSON payload on stdin.','JSON ok/errors result.','Use before tool_installation_validator or normalizer.'));add(mk('payload_fixture','tool_payload_fixture_builder.py','Generate a minimal known-good execution fixture.',templates.fixture,'No input required.','Minimal JSON fixture.','Use for live execution tests.'))}
if(has(combined,['bug','failing','failure','reproduce','crash']))add(mk('minimal_repro','minimal_repro_case.py','Reduce a failure into the smallest reproducible case.',templates.repro,'Small failing case edited in.','Deterministic repro or assertion.','Attach to debugging tools.'));
if(has(combined,['test','coverage','regression','assert','quality']))add(mk('test_harness','result_shape_test_harness.py','Assert expected result shape and prevent regressions.',templates.test,'Expected output fixture.','Pass/fail output.','Run before quality testing.'));
if(has(combined,['slow','performance','benchmark','latency','timeout','profile']))add(mk('benchmark','bounded_benchmark_harness.py','Measure runtime with bounded iterations before optimizing.',templates.bench,'Target function edited in.','Elapsed time and iterations.','Use before performance refactors.'));
if(has(combined,['repo','codebase','files','modules','architecture','inspect source']))add(mk('codebase_inspector','read_only_codebase_inspector.py','Create a read-only file/module inventory for codebase analysis.',templates.inspect,'Run from repo root.','JSON file list and count.','Feed into architecture review.'));
if(has(combined,['dependency','dependencies','package','requirements','libraries']))add(mk('dependency_summary','dependency_summary.py','Summarize dependency manifests without installing anything.',templates.deps,'Run from repo root.','Manifest snippets.','Use for compatibility/risk analysis.'));
if(has(combined,['adapter','integration','downstream','other tools','normalize','convert']))add(mk('adapter','tool_payload_adapter.py','Adapt rough JSON into standard Tool Foundry execution shape.',templates.adapter,'JSON on stdin.','JSON with tool_id and input.','Use between scripts and /tools/execute.'));
if(!scripts.length){add(mk('codebase_inspector','read_only_codebase_inspector.py','Start with a read-only source inventory when the task is underspecified.',templates.inspect,'Run from repo root.','JSON file list and count.','Use inventory to pick the next helper.'));add(mk('test_harness','result_shape_test_harness.py','Add a minimal assertion harness before changing code.',templates.test,'Expected output fixture.','Pass/fail output.','Use before implementation.'))}
const needApproval=approvalNeeded(combined,input.approval_status);const safety={read_only_default:true,executes_generated_scripts:false,writes_files_by_default:false,external_access_by_default:false,destructive_potential:false,owner_approval_required:needApproval,approval_triggers:['destructive writes','deployment','external APIs/accounts','paid services','secrets','messaging','permission changes','scheduled actions']};return{recommended_scripts:scripts,script_purposes:scripts.map(s=>s.purpose),script_templates:scripts.map(s=>({name:s.name,template:s.template})),expected_inputs_outputs:scripts.map(s=>({name:s.name,expected_input:s.expected_input,expected_output:s.expected_output})),safety_classification:safety,ephemeral_or_committed:scripts.map(s=>({name:s.name,classification:s.ephemeral_or_committed})),execution_test_commands:scripts.map(s=>s.test_command),integration_notes:scripts.map(s=>s.integration_note),owner_approval_needed:needApproval,plain_english_summary:`Recommended ${scripts.length} helper script(s). Default posture: read-only, ephemeral, and non-executing until owner approval for riskier actions.`}}
function install(router){if(!router)return{installed:false,reason:'router missing'};if(Array.isArray(router.BUILTIN_TOOL_METADATA)){const i=router.BUILTIN_TOOL_METADATA.findIndex(t=>t.tool_id===METADATA.tool_id);if(i>=0)router.BUILTIN_TOOL_METADATA[i]=METADATA;else router.BUILTIN_TOOL_METADATA.push(METADATA)}if(router.EXECUTABLE_HANDLERS)router.EXECUTABLE_HANDLERS[METADATA.tool_id]=execute;if(typeof router.registerTool==='function')router.registerTool(METADATA);return{installed:true,tool_id:METADATA.tool_id}}
module.exports={METADATA,metadata:METADATA,execute,handle:execute,handler:execute,install};
